### ISSUE TITLE
Refreshing ngModel

### ISSUE THREAD

**Issue by ghost** [Recras/angular-jquery-timepicker#28]
Hi. 

I've been trying to resolv my problem for 4 days....
Still JS and angular beginner.
So, I made the function that updates my timepicker options. Exactly disableTimeRanges. Everytime I push a button I want to 'refresh the timepicker' and update options... but I can't. I've tried many different ways....
Can you help me somehow? I hate spending so much time stuck in one place : (

**Comment by nederdirk** [comment]
Thanks for your question. It would help us to answer your question if we knew what things you have tried. From your description it appears your problem is similar to https://stackoverflow.com/questions/32266692/setting-custom-time-options-for-angular-jquery-timepicker 
Does that Stack Overflow question and answer help you in your situation? If not, could you provide the solutions you've tried (if possible with a code sample or Plunkr sample)?

**Comment by kissmypen** [comment]
So this is what I'm trying to do. Add some array to 'disableTimeRanges'.

http://plnkr.co/edit/bEC9FfiIAmv4k27FsSEc?p=preview

As You can see it doesn't work. 
After many hours i've spent on looking some help on google i found this: 

http://stackoverflow.com/questions/29820182/timepicker-not-updating-ng-model

But $compile compiles my strings in array to seconds (example: "8:00am to 28800).

I've tried thousands of ways to solve it.... The point is that i have to refresh my 'datePickerOptions' in directive after click.

P.S.
Sorry for newbie questions... but how can i learn if not asking more experienced people...
And i need to polish my english...

**Comment by xak2000** [comment]
The directive doesn't watch `timePickerOptions` (`scope.uiTimepicker` in directive's code). So after it first initializes in link function it never change any jquery.timepicker's option. The correct way to change configuration of already initialized jquery.timepicker is using something like this `element.timepicker('option', 'minTime', '2:00am');`.

Maybe we can expose `jquery.timepicker`'s API in `angular-jquery-timepicker` directive?
For example we can set up API object and bind it to some directive's attribute like this:
```
scope: {
  // ...,
  api: '='
},
link: function () {
  // ...
  scope.api = {
    setOption: function (option, value) {
      element.timepicker('option', option, value);
    }
    // any other useful jquery.timepicker's methods
  };
}
```
And use it like this:
`<input ui-timepicker ng-model="someDateObject" api="someVariable">`

**Comment by xak2000** [comment]
Or maybe as we already using `ng-model` we can just add this api methods to `NgModelController` and then we can just use it like:
```
<input ui-timepicker ng-model="someDateObject" name="myTimepicker">
<button ng-click="myTimepicker.setOption('minTime', '2:00am')">set minTime</button>
````
or
`scope.myTimepicker.setOption('minTime', '2:00am');`

**Comment by kissmypen** [comment]
Thanks!... but... as it usually happens to me..........

Your solution worked on plunkr but not in my own project... so i had to do it the other way... also made in plunkr..

Please checkout and let me know what You think.

![error](https://cloud.githubusercontent.com/assets/8864038/12155626/6e3c755a-b4c6-11e5-9604-4ec087fce813.png)

**Comment by xak2000** [comment]
I don't know why this doesn't work in your project without code.. But I can assume that you use `api` before it initialized in directive's link function. For example if you trying to execute api methods from controller of outer directive (which includes `ui-timepicker`).

This is because controllers running in order from parent to child, and postLink functions running in order from child to parent. (see [this](http://stackoverflow.com/a/18491502/758991) answer).

So if you use this api approach then you shoud call api methods only after `ui-timepicker`s postLink function executed. Or just from any handler but not directly in your controller.

But I can't imagine the case when you need to call it from controller as you can just pass initial options through `ui-timepicker="timepickerOptions"`.

**Comment by kissmypen** [comment]
I'm running it from modal (which requires ui.bootrstrap)... Do you think it may be it?

**Comment by xak2000** [comment]
You can run it from any place as long as it running **after** `ui-timepicker`s postLink function was called.
This is because you assign the api from this directive's postLink function:
```
            scope.api = {
              setOptions: function(name, data) {
                element.timepicker('option', name, data);
              }
            };
            console.log('API is initialized!');
```

Until this code wasn't runned the `api` is undefined.
Modal or not - it doesn't matter. The only things that matter is **when** you use the api.

**Comment by timmipetit** [comment]
Thanks for helping us with answering this question @xak2000!

@kissmypen: what @xak2000 said about watching the options is true, the directive currently doesn't watch for changes on the options. Maybe this would be a good idea to do (as long as it doesn't impact performance). If someone would write a pull-request for this, we will happily accept it. Exposing the jquery-timepicker API through the directive also sounds like a good idea.

A quick and dirty solution to get the results you want, would be to use jQuery code directly in your controller. I've created a Plunker to demonstrate it: http://plnkr.co/edit/h1F6X4batGBwJ3p9s4wc?p=preview
